[tool.codespell]
enable-colors = true
write-changes = true
check-hidden = true
quiet-level = 3
builtin = ["clear", "rare", "en-GB_to_en-US"]
skip = [
	".mailmap",
	"*.gitignore",
	"*.po",
	"*.pot",
    "*.csv",
    "*/FONTLOG.txt",
]
ignore-words-list = [
	"brane",
	"breaked",
	"buttonn",
	"cancelled",
	"checkin",
	"colour",
	"curvelinear",
	"dialogue",
	"doubleclick",
	"expct",
	"findn",
	"gird",
	"hel",
	"inout",
	"labelin",
	"lod",
	"mis",
	"nd",
	"numer",
	"ot",
	"outin",
	"parm",
	"requestor",
	"sade",
	"streamin",
	"te",
	"textin",
	"thirdparty",
	"vai",
]
